export const categories = [
  {id: 1, name: 'Deserts', image: require('../Images/1.png')},
  {id: 2, name: 'Ice Cream', image: require('../Images/2.png')},
  {id: 3, name: 'Juices', image: require('../Images/3.png')},
  {id: 4, name: 'Stakes', image: require('../Images/4.png')},
  {id: 5, name: 'burger', image: require('../Images/5.png')},
  {id: 6, name: 'Pizza', image: require('../Images/6.png')},
];

export const featured = {
  id: 1,
  title: 'Hot and Spicy',
  description: 'soft and tender fried chicken',
  resturants: [
    {
      id: 1,
      name: 'Papa Johns',
      image: require('../Images/papa.jpg'),
      description: 'Hot and spicy pizzas',
      lng: 38.21,
      lat: -85.5324,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
      address: '434 second street',
      dishes: [
        {
          id: 1,
          name: 'Fried',
          price: 10,
          description: 'cheezy garlic samosa',
          image: require('../Images/samosa.jpg'),
        },
        {
          id: 2,
          name: 'Dinner',
          price: 20,
          description: 'very tasty karahi',
          image: require('../Images/karahi.jpg'),
        },
        {
          id: 3,
          name: 'Roti',
          price: 5,
          description: 'Delecious Naan',
          image: require('../Images/roti.jpg'),
        },
        {
          id: 4,
          name: 'Barbq',
          price: 40,
          description: 'Very tasty malai boti',
          image: require('../Images/barbq.jpg'),
        },
      ],
    },
    {
      id: 2,
      name: 'KFC',
      image: require('../Images/kfc.png'),
      description: 'Hot and spicy pizzas',
      lng: 38.21,
      lat: -85.5324,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
      address: '434 second street',
      dishes: [
        {
          id: 5,
          name: 'Pizza',
          price: 10,
          description: 'cheezy garlic pizza',
          image: require('../Images/pizza.jpg'),
        },
        {
          id: 6,
          name: 'Burger',
          price: 10,
          description: 'cheezy garlic pizza',
          image: require('../Images/burger.jpg'),
        },
        {
          id: 7,
          name: 'Italian',
          price: 10,
          description: 'cheezy garlic pizza',
          image: require('../Images/italian.jpg'),
        },
        {
          id: 8,
          name: 'Chineese',
          price: 10,
          description: 'cheezy garlic pizza',
          image: require('../Images/chineese.jpg'),
        },
      ],
    },
    {
      id: 3,
      name: 'AL Baik',
      image: require('../Images/albaik2.jpg'),
      description: 'Hot and spicy pizzas',
      lng: 38.21,
      lat: -85.5324,
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
      address: '434 second street',
      dishes: [
        {
          id: 9,
          name: 'Pasta',
          price: 10,
          description: 'cheezy garlic pastaa',
          image: require('../Images/pasta.jpg'),
        },
        {
          id: 10,
          name: 'Fish',
          price: 20,
          description: 'heavy Fish',
          image: require('../Images/fish.jpg'),
        },
        {
          id: 11,
          name: 'Snacks',
          price: 40,
          description: 'cheezy Snacks',
          image: require('../Images/snacks.jpg'),
        },
        {
          id: 12,
          name: 'Wings',
          price: 50,
          description: 'cheezy Wings',
          image: require('../Images/wings.jpg'),
        },
      ],
    },
  ],
};
